name: Tests
on:
  push:
  pull_request:

jobs:
  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      # Set up Flutter.
      - name: Clone Flutter repository with 1.22.6 version
        uses: subosito/flutter-action@v1.5.0
        with:
          flutter-version: 1.22.6
          channel: stable
      - run: flutter doctor -v

      - name: Get pub packages
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: flutter pub get
      - run: flutter analyze
      
      - name: Ensure the Dart code is formatted correctly
        run: flutter format --set-exit-if-changed --dry-run .
        
      - name: Run Flutter unit tests
        run: flutter test
